package ix.back_end;

import java.time.LocalDateTime;
import java.util.Optional;

import org.springframework.web.bind.annotation.RestController;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;


@RestController // This means that this class is a Controller
@RequestMapping(path="/metavivasi") // This means URL's start with /review (after Application path)
public class MetavivasiController {
	@Autowired // This means to get the bean called reviewRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private MetavivasiRepository metavivasiRepository;
	

        @PostMapping(path="/add") // Map ONLY POST Requests
	 public @ResponseBody String addNew(@RequestBody Metavivasi newMetavivasi){
            // @ResponseBody means the returned String is the response, not a view name
	    // @RequestParam means it is a parameter from the GET or POST request
            
	    Metavivasi item = new Metavivasi(newMetavivasi.getSeller_id(), newMetavivasi.getCar_label(), 
                    newMetavivasi.getBuyer_afm(), newMetavivasi.getDm_id());
	    metavivasiRepository.save(item);
	    return "Saved";
	  }


	 
	  @GetMapping(path="/all") //Map ONLY GET Requests
	  public @ResponseBody Iterable<Metavivasi> getAll() {
	    // This returns a JSON or XML with the reviews
	    return metavivasiRepository.findAll();
	  }
	  
	  
	  @GetMapping("/get/{id}")
	  Optional<Metavivasi> one(@PathVariable Integer id) {
		// Single record
	    return metavivasiRepository.findById(id);
	  }
	
	  @PostMapping("/edit/{id}")
	  Metavivasi replace(@RequestBody Metavivasi newMetavivasi, @PathVariable Integer id) {
	    //edit or create if not exists
	    return metavivasiRepository.findById(id)
	      .map(metavivasi -> {
	    	metavivasi.setSeller_id(newMetavivasi.getSeller_id());
	    	metavivasi.setAccepted(newMetavivasi.getAccepted());
	    	metavivasi.setCar_label(newMetavivasi.getCar_label());
	    	metavivasi.setBuyer_afm(newMetavivasi.getBuyer_afm());
	    	metavivasi.setDm_id(newMetavivasi.getDm_id());
	        return metavivasiRepository.save(metavivasi);
	      })
	      .orElseGet(() -> {
	        newMetavivasi.setId(id);
	        return metavivasiRepository.save(newMetavivasi);
	      });
	  }
    
}
